config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/subs')
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :comments, only: [:create]
  resources :subs, except: [:destroy]
  
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
    
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author, :post, presence: true
  
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  
  has_many(
    :child_comments,
    class_name: 'Comment',
    foreign_key: :parent_comment_id,
    primary_key: :id
  )
  belongs_to(
    :parent_comment,
    class_name: 'Comment',
    foreign_key: :parent_comment_id,
    primary_key: :id
  )
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  
  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id
  )
  
  has_many(
    :top_level_comments,
    -> { where(parent_comment_id: nil) },
    class_name: 'Comment'
  )
  
  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments
end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true
  
  belongs_to :post, inverse_of: :post_subs
  belongs_to :sub, inverse_of: :post_subs
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true
  
  belongs_to(
    :moderator,
    class_name: 'User'
  )
  has_many :post_subs
  has_many :posts, through: :post_subs, source: :post
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true

  after_initialize :ensure_session_token
  
  has_many(
    :subs,
    foreign_key: :moderator_id
  )
  
  has_many(
    :post,
    foreign_key: :author_id
    )
    
  has_many(
    :comments,
    foreign_key: :author_id
    )
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def is_password?(password)
    BCrypt::Password.new(password_digest) == password
  end 
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= reset_session_token!
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?(user)
    return false if user.nil?
    session[:session_token] == user.session_token
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    render :new
  end  

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      render :new
    end
  end
   
  private
  
  def comment_params
    params.require(:comment).permit(:content, :author_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    if current_user
      @post = Post.new
      render :new
    else
      redirect_to new_session_url
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    
    if user.nil?
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_moderator, only: [:edit]
  
  def new
    if current_user
      @sub = Sub.new
      render :new
    else
      redirect_to new_session_url
    end
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end
  
  def index
    @subs = Sub.all
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end
  
  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
  
  def require_moderator
    unless Sub.find(params[:id]).moderator == current_user
      redirect_to sub_url(params[:id])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def authenticate
    ("<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def is_author?(user, post)
    return nil if user.nil?
    post.author == user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def is_moderator?(user, sub)
    return nil if user.nil?
    sub.moderator_id == user.id
  end
  
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<form action="/comments" method="POST">  
  <%= authenticate %>
  
  <input type='hidden' name='comment[post_id]' value='<%= params[:post_id] %>'>
  <label>content<textarea name='comment[content]'> </textarea></label>

  <input type='submit'>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<br>
<br>
<br>
<br>
<% if logged_in?(current_user) %>
  <%= button_to "logout", session_url, method: :delete %>
<% else %>
  <%= button_to "sign in", new_session_url, method: :get %>
  <%= button_to "sign up", new_user_url, method: :get%>
<% end %>
</body>

<%= button_to 'home', root_url, method: :get %>

</html>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>


<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  
  <%= authenticate %>
  
  <label>title<input type='text' name='post[title]'></label>
  
  <label>content<textarea name='post[content]'> </textarea></label>
  <br>
  
  <br>
  
  <input type='hidden' name='post[sub_ids][]' value=''>
    <% Sub.all.each do |sub| %>
      <label>
        <input type='checkbox' 
        name='post[sub_ids][]' 
        value='<%= sub.id %>'
         <% 'checked' if @post.sub_ids.include?(sub.id) %>>   
        <%= sub.title %>
      </label>
    <br>
    <% end %>
  
  
  <input type='submit'>

</form>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>


<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>


<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= @post.content %>

<h3>Comments</h3>
<ul>
<% @post.comments.each do |comment| %>
  <li><%= comment.content %></li>
  <% end %>
</ul>

<%= button_to 'comment', new_post_comment_url(@post), method: :get %>
<%= button_to 'subs', subs_url, method: :get %>

<br>
<% if is_author?(current_user, @post) %>
 <%= button_to "edit", edit_post_url(@post), method: :get %>
 <% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>


<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  
  <%= authenticate %>
  
  <label>title<input type='text' name='sub[title]'></label>
  
  <label>description<textarea name='sub[description]'> </textarea></label>
  <br>
  <input type='submit'>

</form>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>Subs</h1>

<ul>
<% @subs.each do |sub| %>
  <li><%= link_to sub.title, sub_url(sub) %></li>
<% end %>
</ul>

<%= button_to 'create sub', new_sub_url, method: :get %>

app/views/subs/new.html.erb
<h1>Create Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h3>moderator: <%= @sub.moderator.username%></h3>

<%= @sub.description %>
<br>
<br>


<ul>
<% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %></li>
<% end %>
</ul>


<br>
<% if is_moderator?(current_user, @sub) %>
 <%= button_to "edit", edit_sub_url(@sub), method: :get %>
 <% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="POST">
  
  <%= authenticate %>
  
  <label>username<input type='text' name='user[username]'></label>
  <label>password<input type='password' name='user[password]'></label>
  <br>
  <input type='submit'>

</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>